### ISSUE TITLE
Project description, problem and deliverables check-off

### ISSUE THREAD

**Issue by jgome043** [jgome043/cs170-group-project#1]
https://github.com/jgome043/cs170-group-project/commit/6572cdd9d2b5db7657f11f5fd0e209f9906fcda7
Review and edit README. Make edits where you see fit. 

Once everyone has signed off on it or we approach the submission deadline, it will be converted to PDF and sent on it's way!!!

Sign-off in this issue once you're satisfied with the doc.

**Comment by iS2bit** [comment]
looks boootiful

**Comment by jgome043** [comment]
Moved sign-off to @tlove004 pull request here: #2 

Please sign-off there.
